# Docker Compose for local development and testing
version: "3.8"

services:
  binance-trading-bot:
    build: .
    ports:
      - "8000:8000"
    environment:
      - BINANCE_API_KEY=${BINANCE_API_KEY}
      - BINANCE_SECRET_KEY=${BINANCE_SECRET_KEY}
      - SIMULATION_MODE=true
      - DRY_RUN=true
      - MAX_TRADES=5
      - LEVERAGE=10
      - TYPE=ISOLATED
      - SL=0.02
      - TP=0.04
      - SPREAD_ADJUSTMENT=0.001
      - RISK_REWARD_RATIO=2.0
      - MAX_PORTFOLIO_RISK=0.1
      - SORTBY=volume
      - PAIRS_TO_PROCESS=10
      - DYNAMIC_POSITION_SIZING=true
    volumes:
      - ./logs:/app/logs
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health"]
      interval: 30s
      timeout: 10s
      retries: 3
